version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: soccer_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: playuser
      MYSQL_PASSWORD: playpass
      MYSQL_DATABASE: soccer_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
  cache:
    image: redis:alpine
    container_name: soccer_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data: