version: '3.8'

services:
  app:
    build: .
    container_name: soccer_app
    env_file:
      - .env.prod
    command: gunicorn -w 4 -b 0.0.0.0:${APP_PORT} main:app
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  db:
    image: mysql:latest
    container_name: soccer_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    expose:
      - "3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u ${MYSQL_USER} --password=${MYSQL_PASSWORD}
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 15
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    restart: unless-stopped
  cache:
    image: redis:alpine
    container_name: soccer_cache
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  backend:
    name: backend
    driver: bridge