name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
          sudo apt-get update
          sudo apt-get install docker-compose-plugin
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Start Docker Compose
      run: sudo docker-compose up -d
      
    - name: Wait for services to be ready
      run: |
        sleep 20 
        docker ps 

    - name: Run Pytest
      run: pytest

    - name: Stop Docker Compose
      if: always() 
      run: docker-compose down