name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
          sudo apt-get update
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Create .env file for Docker Compose
      run: |
        echo "APP_PORT=${{ vars.APP_PORT }}" >> .env.prod
        echo "DEBUG=${{ vars.DEBUG }}" >> .env.prod
        echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env.prod
        echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env.prod
        echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env.prod
        echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env.prod
        echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> .env.prod
        echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env.prod
        echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env.prod
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env.prod
        echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env.prod
        
    - name: Start Docker Compose
      run: docker-compose up -d --build
      
    - name: Wait for services to be ready
      run: |
        sleep 15
        docker ps -a
    
    - name: Monitor Resource Usage
      run: |
        free -m
        df -h
        docker stats --no-stream

    - name: Run Pytest
      run: | 
        docker exec soccer_app python -m pytest -v -s

    - name: Stop Docker Compose
      if: always() 
      run: docker-compose down -v